[AC-37] - DRAFT - DO NOT MERGE - Build and create image of Docker for AdminConsole
Ed-Fi-Alliance-OSS/Ed-Fi-Admin-Console pull request #15
Opened 2024-10-14 15:56 UTC by DavidJGapCR

2024-10-16 22:58 UTC, jagudelo-gap requested changes

2024-10-16 22:58 UTC, jagudelo-gap commented on package.json
>    "dependencies": {
Rebase this file because the most recent changes need to be pointed to the react version 18.3.1 and this file seems to be outdated

2024-10-16 22:58 UTC, jagudelo-gap commented on package-lock.json
> +        "@edfi/admin-console-shared-sdk": "2.2.5",
Rebase this file because the most recent changes need to be pointed to the react version 18.3.1 and this file seems to be outdated

2024-10-16 22:58 UTC, jagudelo-gap commented on docker/Compose/KeyCloak/realm-and-users.json
> +        "privateKey" : [ "MIIEowIBAAKCAQEAsaJP5TeFYADnZxpa5SPabDm8KqYmQaxFYLa7Ecps3FRBcTz8isJ/OdYTb2un1fvMttG5b9tgUn/kglhG+06+2SOaxntuLXjnaTlySVjCM176lnkJBCLHTSBcrzVjEUD1vPaW5rYowfGhG7KkaYJudGzJr5+Pn
Where did you get this value? Is there any tool to help us to generate a new one or has to be set manually?

2024-10-17 14:40 UTC, DavidJGapCR commented on docker/Compose/KeyCloak/realm-and-users.json
> +        "privateKey" : [ "MIIEowIBAAKCAQEAsaJP5TeFYADnZxpa5SPabDm8KqYmQaxFYLa7Ecps3FRBcTz8isJ/OdYTb2un1fvMttG5b9tgUn/kglhG+06+2SOaxntuLXjnaTlySVjCM176lnkJBCLHTSBcrzVjEUD1vPaW5rYowfGhG7KkaYJudGzJr5+Pn
Good point. KeyCloak has tools to export and import these configurations. So, what I did was to create the configuration manually first, and then I exported it so I was able to include the file as part of the start up process, which is what you see in the docker file. If you see the docker file it first copies the file on line 4: 
`COPY realm-and-users.json /opt/keycloak/data/import/`
And then on line 11, with this command.
`CMD ["start-dev --import-realm"]`
we tell KeyClock something like: **"On start up, try to import every json file you find in /data/import/ "**
I will mention this on the readme file in case we have to regenerate this file in the future.

2024-10-17 19:02 UTC, jagudelo-gap approved these changes

2024-10-17 20:35 UTC, jpardogrowthaccelerationpartners approved these changes

2024-10-17 21:19 UTC, merged