[AC-39] Fix e2e tests
Ed-Fi-Alliance-OSS/Ed-Fi-Admin-Console pull request #17
Opened 2024-10-16 21:50 UTC by dfernandez-gap

- Fix authentication setup.
- Add home page tests.
- Fix instance tests for schedule tab
- Comment not working tests.

2024-10-16 21:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-Admin-Console?pullRequest=17) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-Admin-Console?pullRequest=17) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Alliance-OSS/Ed-Fi-Admin-Console?pullRequest=17) it.</sub>

2024-10-16 23:04 UTC, jagudelo-gap requested changes
https://edfi.atlassian.net/wiki/spaces/dev/pages/19334435/Individual+Contributors+License+Agreement

2024-10-16 23:04 UTC, jagudelo-gap commented on package.json
> +    "react": "18.2.0",
Rebase this file because the most recent changes need to be pointed to the react's version 18.3.1 and this file seems to be outdated

2024-10-16 23:04 UTC, jagudelo-gap commented on package-lock.json
Rebase this file because the most recent changes need to be pointed to the react's version 18.3.1 and this file seems to be outdated

2024-10-16 23:17 UTC, dfernandez-gap commented on package.json
> +    "react": "18.2.0",
Requested change is ready

2024-10-16 23:17 UTC, dfernandez-gap commented on package-lock.json
Requested change is ready

2024-10-18 15:01 UTC, jagudelo-gap approved these changes

2024-10-18 22:12 UTC, merged